### ISSUE TITLE
Allow multiple key for ticket decoding

### ISSUE THREAD

**Issue by jot2re** [SmartTokenLabs/attestation#197]
Currently the `TicketDecoder` class only allows a single public key to be given as parameter. 
However, this key will vary depending on the ticket issuer, which can be one of many. 
We should update the code to support multiple public keys depending on the DevCon ID.

**Comment by oleggrib** [comment]
I think that good way to fix it is to use TokenScript XML file with token configuration, including issuer public key. 
As option - we can save token config in the SmartContract
@colourful-land , does it make sense?
